### ISSUE TITLE
Best way to determine a microbe. 

### ISSUE THREAD

**Issue by jason-braun-sociomantic-mouse** [sociomantic/microbe#99]
Me and nico were taking about the best way to determine a microbe.  Now is a bit of a mouthful
```js
if ( µVar.type === '[object Microbe]' )
```

Options discussed were:

attach a microbe to itself with a chained scope -
```js
µ( 'html' ).µ( 'div' ) // scoped. Essentially .find()

if ( µVar.µ )
```

attach like jquery
```js
µVar.microbe // "0.4.14"

if ( µVar. microbe )
```

boolean
```js
µVar.isMicrobe // true

if ( µVar.isMicrobe )
```

I like µVar.isMicrobe. Other opinions / ideas?

**Comment by AvraamMavridis** [comment]
What about using the `constructor`?

e.g.

```
function Microbe(){}
var m = new Microbe();

console.log( m.constructor === Microbe ); //true
```

**Comment by mousemke** [comment]
interesting.  that wouldn't actually work as written, since the actual exposed side of microbe is µ, and not Microbe
```js
console.log( Microbe );  // undefined
```

but we could do something like:
```js
if ( µVar.constructor === µ ) // true
```

However if µ is not defined, then this will throw an error.  I think it needs to be something on the object that can be tested without comparing it to a 2nd variable.

Also (for the sake of clarity) we were looking at possible best practices to check if a microbe is a microbe in production, not internally

**Comment by AvraamMavridis** [comment]
Ah, I see. I thought it was for internal use.
:+1:

**Comment by jason-braun-sociomantic-mouse** [comment]
ok, then (unless there's any objections) i'm gonna roll with isMicrobe as `true` built into the core at the same place as the version

**Comment by AvraamMavridis** [comment]
:+1: 
One suggestion, maybe the `isMicrobe` should be readonly (?)

**Comment by jason-braun-sociomantic-mouse** [comment]
yes.  way good call.  i think the same should be true for the type and version
